### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by juanpicado** [kgrubb/verdaccio-assets#1]
Can you try with different sort of fonts? I'm curious.

**Comment by kgrubb** [comment]
Sure! Do you have any specific fonts in mind? I'll look for some more fresco styled fonts. I'll also try to find a more sans serif font family too.

**Comment by 030** [comment]
calibri, arial

**Comment by kgrubb** [comment]
My personal workstation is a Mac, so I don't have access to the MS fonts (Calibri). However, here's a few more fonts:

## Arial
![](https://raw.githubusercontent.com/kgrubb/verdaccio-assets/master/verdaccio-logo-arial-full.png)


## Kokonor
![](https://raw.githubusercontent.com/kgrubb/verdaccio-assets/master/verdaccio-logo-kokonor-full.png)

## Songti
![](https://raw.githubusercontent.com/kgrubb/verdaccio-assets/master/verdaccio-logo-songti-full.png)

## Original Niconne Logo (for reference)
![](https://raw.githubusercontent.com/kgrubb/verdaccio-assets/master/verdaccio-circle-flat-full.png)

**Comment by 030** [comment]
I prefer songti

**Comment by kgrubb** [comment]
I agree. I feel like it is a good mix between serif and sans serif. @juanpicado, what are your thoughts on the songti font?

**Comment by juanpicado** [comment]
I think italics looks nicer with this design. Either Kokonor, Songti or the original.

**Comment by silkentrance** [comment]
@kgrubb could you do it in a more fresco-ish style, provided that it still has clean contours? https://www.youtube.com/watch?v=Cej4Ggq5nQI

**Comment by kgrubb** [comment]
hm, that's a tough ask. Fresco paintings aren't exactly friendly with svg's. I'll ty and mock something up, but no promises 😛
